[package]
name = "forgers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcf = "0.6.1"
log = "0.4"
env_logger = "0.11.5"
structopt = "0.3.26"
flate2 = "1.0.31"
bitvec = "1.0.1"
